<plugins>
	<prefixes>
		<prefix type="SidePanel">SidePanel_</prefix>
		<prefix type="Options">Options_</prefix>
	</prefixes>
	<locations>
		<location type="zip">TotalByteInformer.jar</location>
		<location type="directory"></location>
		<location type="directory">plugins</location>
	</locations>
</plugins>